
name: Validate renovate config
on:
  workflow_dispatch:
  pull_request:
    paths: 
      - 'renovate.json5'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1